name: disaster
channels:
        - conda-forge
dependencies:
        - python=3.7.7
        - jupyter=1.0.0
        - matplotlib=3.1.3
        - numpy=1.18.1
        - pandas=1.0.3
        - scipy=1.4.1
        - scikit-learn=0.22.1
        - tensorflow=2.0.0
        - pillow=7.1.2
        - nltk=3.4.5
        - tqdm=4.31.1
